---
apiVersion: v1
kind: Pod
metadata:
  name: network-tools-1
  namespace: kube-system
spec:
  containers:
    - name: network-tools
      image: aries1980/network-tools:latest
      imagePullPolicy: IfNotPresent
      args: ["/bin/sh", "-c", "sleep 1000000000"]
  nodeSelector:
    kubernetes.io/hostname: node-1.mylittle.cluster
---
apiVersion: v1
kind: Pod
metadata:
  name: network-tools-2
  namespace: kube-system
spec:
  containers:
    - name: network-tools
      image: aries1980/network-tools:latest
      imagePullPolicy: IfNotPresent
      args: ["/bin/sh", "-c", "sleep 1000000000"]
  nodeSelector:
    kubernetes.io/hostname: node-2.mylittle.cluster

